server:
  persistentVolume:
    enabled: false 
extraScrapeConfigs: |
  - job_name: 'istiod'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istiod;http-monitoring
  - job_name: 'envoy-stats'
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod

    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'




  - job_name: 'linkerd'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names: ['{{".linkerd-viz"}}']

    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_container_name
      action: keep
      regex: ^prometheus$

    honor_labels: true
    metrics_path: '/metrics'

    params:
      'match[]':
        - '{job="linkerd-proxy"}'
        - '{job="linkerd-controller"}'
