apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "123456"]
---
apiVersion: v1
kind: Service
metadata:
  name: app: ubuntu
spec:
  selector:
    app:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80